### ISSUE TITLE
cannot build with bytestring-0.11.2.0: Ambiguous occurrence ‘scientific’

### ISSUE THREAD

**Issue by jwaldmann** [haskell/aeson#911]
I was trying to use bytestring-0.11.2.0 but this gives
```
...
aeson             > /tmp/stack-4c186e59af6847f0/aeson-2.0.2.0/src/Data/Aeson/Encoding/Builder.hs:69:30: error:
aeson             >     Ambiguous occurrence ‘scientific’
aeson             >     It could refer to
aeson             >        either ‘B.scientific’,
aeson             >               imported from ‘Data.ByteString.Builder’ at src/Data/Aeson/Encoding/Builder.hs:47:1-35
aeson             >               (and originally defined in ‘Data.ByteString.Builder.RealFloat’)
aeson             >            or ‘Data.Aeson.Encoding.Builder.scientific’,
aeson             >               defined at src/Data/Aeson/Encoding/Builder.hs:143:1
aeson             >    |
aeson             > 69 | encodeToBuilder (Number n) = scientific n
aeson             >    |                              ^^^^^^^^^^
```
because `scientific` is a fresh export https://hackage.haskell.org/package/bytestring-0.11.2.0/docs/Data-ByteString-Builder-RealFloat.html#v:scientific

**Comment by phadej** [comment]
oops

**Comment by jwaldmann** [comment]
simply this?
```
-import Data.ByteString.Builder as B
+import Data.ByteString.Builder as B hiding (scientific)
```

**Comment by phadej** [comment]
@jwaldmann No. Explicit import list or qualified import.

**Comment by phadej** [comment]
I made revisions to `aeson-2` releases. Will make revisions for older `aeson`s later today.

**Comment by jwaldmann** [comment]
Still, we'd want to use the new bytestring together with aeson? In my current project, I need aeson, but its performance isn't critical.  I also need bytestring, and it *is* critical. So I want to pick up their improvements. This would be blocked if aeson restricts bytestring to an earlier version.

**Comment by phadej** [comment]
resolved in 2.0.3.0 release

**Comment by coderfromhere** [comment]
Could you backport it to the 1.5 branch too? Stack from Nix is now blocked on it, and I have to rebuild it from a fork - https://github.com/coderfromhere/aeson/pull/1 until the most of the ecosystem moves to v2.
